### ISSUE TITLE
gluex_MC.py master crashes on vertex indices 

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#114]
I tried using the master after meeting the missing-endif bug in $MCWRAPPER_CENTRAL which I think is 2.8.0.  The master crashed as below.  Then I checked out the previous commit (fixing the endif) & that ran fine so far, it launched the jobs.  Do we need to update config files?  

The output below from using the master branch
`[njarvis@ifarm1901.jlab.org: ~/mywork/makeMC/phi_v68_newmc ]> ~/mywork/gluex_MCwrapper/gluex_MC.py MC_2k.config 30730-30788 10000000 batch=2 per_file=100000
*********************************
Welcome to v2.8.0 of MCwrapper
Thomas Britton 03/21/24
*********************************
unknown config parameter!! LOG_DIR
('WILL BE BUNDLED', False)
Creating v68_newmc to simulate 10000000 gen_2k_4_4 Events
Traceback (most recent call last):
  File "/home/njarvis/mywork/gluex_MCwrapper/gluex_MC.py", line 1892, in <module>
    main(sys.argv[1:])
  File "/home/njarvis/mywork/gluex_MCwrapper/gluex_MC.py", line 1517, in main
    COMMAND_dict['upper_vertex_indices']=str(UPPER_VERTEX_INDICES)
UnboundLocalError: local variable 'UPPER_VERTEX_INDICES' referenced before assignment`

**Comment by jrstevenjlab** [comment]
Sorry, no I just didn't check that the variables were initialized in the last PR I merged.  I just submitted a PR where this is fixed that I tested works on the master branch

**Comment by nsjarvis** [comment]
Thanks
